# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

os: linux
dist: bionic
language: generic # optional, just removes the language badge

services:
  - docker

notifications:
  slack:
    secure: Giv3kL87piDCRK0r7o1chD734C0X/54DTVqAuW5tKmGDuie2GC8TtfFtltf9VHDis9Lonryr07zs0H7cUgtLRvse6vFkg2ISoXY2L7kBavIWCFjR9m69lEVymlfOONwAQ0Bx+x6gG6YlcTUg50IVj1MXHnosXtzPQ1HS0erhUT/x1M3HOjqcLp8rt5k71VczAE3ET/G6cCENaV1TwIvFqrgBu/hK0gTPIwGLcstXzsoBiBkgaFGkEcm0pgZS05K/TEeMq+R1ynNlcajEPwNfxicAQlKmfvq5IL7+bs9K6Wag7xJPbcmFV8lJF/MNP2WeGrT/XTSJgKdQW0/C+CuB/ljiYu2kfu1RsMCyCoMo1cNM8gjoivct13RtqKtpTL9x5ZF/guKw49kg5PRUVOXVfo88l8te26ib/lbRAMHDZn5D/iflAJcJX4eMk/SA8dkrJi0ftYYBJo5xGghUcTg1p+1u74wpgLmUNKu3XuXQDcq6+Ldipy/H/Zcq0m2iBRGblDTnaYewPVegKHJ2GnYKzluFtiielnuK+LxP+uyBXxX3vPXnFxRv/Z55w3WBvVf0garHmaQzSwMv0VE1qntmNDKgKB8yFR+QyL+Ze3jVmuBj2fZT61vDbuADx53vjBD4XnlC0zscuYBdKsLzPiZZbkqiiCWweBU6VcLhrArRdho=
  email: false

# include the following block if the C/C++ build artifacts should get cached by Travis,
# CCACHE_DIR needs to get set as well to actually fill the cache
cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true # optional, silences the cloning of the target repository

# configure the build environment(s)
# https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#variables-you-can-configure
env:
  global:
    - ROS_REPO=ros
    - CCACHE_DIR=$HOME/.ccache # enables C/C++ caching in industrial_ci
    - BUILDER=colcon
    - CATKIN_LINT=pedantic
    - CATKIN_LINT_ARGS='--ignore missing_catkin_include'
    - UPSTREAM_WORKSPACE='.rosinstall -march/march_data_collector -march/march_gain_scheduling -march/march_gait_scheduler -march/march_gait_selection -march/march_launch -march/march_safety -march/march_shared_classes -march/march_state_machine'

jobs:
  include:
    - name: "Melodic"
      env: ROS_DISTRO=melodic
    - name: "clang-format"
      env: ROS_DISTRO=melodic CLANG_FORMAT_CHECK=file

# clone and run industrial_ci
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
